const fs = require('fs');

// Read the file
let content = fs.readFileSync('vermilion.asm', 'utf8');

// Map of hex/decimal values to constant names
const valueToConstant = {
  '0': 'GAMEPLAY_STATE_INIT_TOWN_ENTRY',
  '$00': 'GAMEPLAY_STATE_INIT_TOWN_ENTRY',
  '1': 'GAMEPLAY_STATE_LOAD_TOWN',
  '$01': 'GAMEPLAY_STATE_LOAD_TOWN',
  '2': 'GAMEPLAY_STATE_TOWN_EXPLORATION',
  '$02': 'GAMEPLAY_STATE_TOWN_EXPLORATION',
  '3': 'GAMEPLAY_STATE_INIT_BUILDING_ENTRY',
  '$03': 'GAMEPLAY_STATE_INIT_BUILDING_ENTRY',
  '4': 'GAMEPLAY_STATE_BUILDING_INTERIOR',
  '$04': 'GAMEPLAY_STATE_BUILDING_INTERIOR',
  '5': 'GAMEPLAY_STATE_TRANSITION_TO_SECOND_FLOOR',
  '$05': 'GAMEPLAY_STATE_TRANSITION_TO_SECOND_FLOOR',
  '6': 'GAMEPLAY_STATE_SECOND_FLOOR_ACTIVE',
  '$06': 'GAMEPLAY_STATE_SECOND_FLOOR_ACTIVE',
  '7': 'GAMEPLAY_STATE_TRANSITION_TO_THIRD_FLOOR',
  '$07': 'GAMEPLAY_STATE_TRANSITION_TO_THIRD_FLOOR',
  '8': 'GAMEPLAY_STATE_THIRD_FLOOR_ACTIVE',
  '$08': 'GAMEPLAY_STATE_THIRD_FLOOR_ACTIVE',
  '9': 'GAMEPLAY_STATE_TRANSITION_TO_CASTLE_MAIN',
  '$09': 'GAMEPLAY_STATE_TRANSITION_TO_CASTLE_MAIN',
  '$0A': 'GAMEPLAY_STATE_CASTLE_ROOM1_ACTIVE',
  '$0B': 'GAMEPLAY_STATE_LOAD_CASTLE_ROOM2',
  '$0C': 'GAMEPLAY_STATE_CASTLE_ROOM2_ACTIVE',
  '$0D': 'GAMEPLAY_STATE_LOAD_CASTLE_ROOM3',
  '$0E': 'GAMEPLAY_STATE_CAVE_ENTRANCE',
  '$0F': 'GAMEPLAY_STATE_BATTLE_INITIALIZE',
  '$F': 'GAMEPLAY_STATE_BATTLE_INITIALIZE',
  '$10': 'GAMEPLAY_STATE_BATTLE_ACTIVE',
  '$11': 'GAMEPLAY_STATE_BATTLE_EXIT',
  '$12': 'GAMEPLAY_STATE_OVERWORLD_RELOAD',
  '$13': 'GAMEPLAY_STATE_OVERWORLD_ACTIVE',
  '$14': 'GAMEPLAY_STATE_TOWN_FADE_IN_COMPLETE',
  '$15': 'GAMEPLAY_STATE_ENTERING_CAVE',
  '$16': 'GAMEPLAY_STATE_CAVE_EXPLORATION',
  '$17': 'GAMEPLAY_STATE_CAVE_FADE_OUT_COMPLETE',
  '$18': 'GAMEPLAY_STATE_ENCOUNTER_INITIALIZE',
  '$19': 'GAMEPLAY_STATE_ENCOUNTER_GRAPHICS_FADE_IN',
  '$1A': 'GAMEPLAY_STATE_ENCOUNTER_PAUSE_BEFORE_BATTLE',
  '$1B': 'GAMEPLAY_STATE_LEVEL_UP_BANNER_DISPLAY',
  '$1C': 'GAMEPLAY_STATE_LEVEL_UP_STATS_WAIT_INPUT',
  '$1D': 'GAMEPLAY_STATE_LEVEL_UP_COMPLETE',
  '$1E': 'GAMEPLAY_STATE_RETURN_TO_FIRST_PERSON_VIEW',
  '$1F': 'GAMEPLAY_STATE_FADE_IN_COMPLETE',
  '$20': 'GAMEPLAY_STATE_DIALOG_DISPLAY',
  '$21': 'GAMEPLAY_STATE_BOSS_BATTLE_INIT',
  '$22': 'GAMEPLAY_STATE_BOSS_BATTLE_ACTIVE',
  '$23': 'GAMEPLAY_STATE_RETURN_FROM_BOSS_BATTLE',
  '$24': 'GAMEPLAY_STATE_BEGIN_RESURRECTION',
  '$25': 'GAMEPLAY_STATE_PROCESS_RESURRECTION',
  '$26': 'GAMEPLAY_STATE_NOTIFY_INAUDIOS_EXPIRED',
  '$27': 'GAMEPLAY_STATE_WAIT_FOR_NOTIFICATION_DISMISS',
  '$28': 'GAMEPLAY_STATE_READ_AWAKENING_MESSAGE',
  '$29': 'GAMEPLAY_STATE_FRYING_PAN_DELAY',
  '$2A': 'GAMEPLAY_STATE_READ_FRYING_PAN_MESSAGE',
  '$2B': 'GAMEPLAY_STATE_SOLDIER_TAUNT',
  '$2C': 'GAMEPLAY_STATE_READ_SOLDIER_TAUNT',
  '$2D': 'GAMEPLAY_STATE_SHOW_POISON_NOTIFICATION'
};

let replacements = 0;

// Replace all MOVE.w #value, Gameplay_state.w with constant
for (const [value, constantName] of Object.entries(valueToConstant)) {
  // Escape $ for regex
  const escapedValue = value.replace('$', '\\$');
  
  // Match: MOVE.w #value, Gameplay_state.w (with optional comment)
  const regex = new RegExp(`(MOVE\\.w\\s+)#${escapedValue}(,\\s+Gameplay_state\\.w)`, 'g');
  
  const matches = content.match(regex);
  if (matches) {
    content = content.replace(regex, `$1#${constantName}$2`);
    replacements += matches.length;
    console.log(`${value} -> ${constantName}: ${matches.length} replacements`);
  }
}

// Write back
fs.writeFileSync('vermilion.asm', content);

console.log(`\nTotal: ${replacements} replacements`);
