// replace_maps.js - Replace map sector dc.b data with incbin directives in vermilion.asm
// Uses map_replacements.json generated by extract_maps.js

const fs = require('fs');

const replacements = JSON.parse(fs.readFileSync('map_replacements.json', 'utf8'));
const src = fs.readFileSync('vermilion.asm', 'utf8');
const lines = src.split('\n');

// Build a set of line indices where sector labels start
// For each sector, find all the dc.b lines that belong to it
const sectorRanges = [];

for (let r = 0; r < replacements.length; r++) {
    const rep = replacements[r];
    const labelLine = rep.asmLine; // 0-indexed
    
    // Find the end of dc.b data for this sector
    // It ends at the next label definition or next sector
    let dataStart = labelLine + 1;
    let dataEnd = dataStart;
    
    for (let i = dataStart; i < lines.length; i++) {
        const trimmed = lines[i].trim();
        if (trimmed === '') continue;
        if (trimmed.startsWith(';')) continue;
        // Only consume dc.b lines (map data is all dc.b)
        // Do NOT consume dc.w or dc.l which are pointer tables
        if (trimmed.startsWith('dc.b')) {
            dataEnd = i + 1; // include this line
            continue;
        }
        // If it's a label definition (word followed by colon, possibly with comment)
        if (/^\w+:/.test(trimmed)) {
            break;
        }
        // Any other content (dc.w, dc.l, instructions, etc.), stop
        break;
    }
    
    sectorRanges.push({
        ...rep,
        dataStart,
        dataEnd, // exclusive
        dataLines: dataEnd - dataStart
    });
}

// Now build the new file
// Mark lines to remove and lines to replace
const lineActions = new Array(lines.length).fill(null); // null = keep

for (const sec of sectorRanges) {
    if (sec.action === 'incbin') {
        // Keep the label line, replace first data line with incbin, remove rest
        // But first, handle comment lines above the label
        lineActions[sec.dataStart] = { type: 'replace', content: `\tincbin "${sec.file}"` };
        for (let i = sec.dataStart + 1; i < sec.dataEnd; i++) {
            lineActions[i] = { type: 'remove' };
        }
    } else if (sec.action === 'remove') {
        // Remove the label and all its data (unreferenced sub-labels like Z80DrvrData_*)
        // Remove the label line
        lineActions[sec.asmLine] = { type: 'remove' };
        // Also remove any comment line above it
        if (sec.asmLine > 0 && lines[sec.asmLine - 1].trim().startsWith(';')) {
            lineActions[sec.asmLine - 1] = { type: 'remove' };
        }
        // Remove its data lines
        for (let i = sec.dataStart; i < sec.dataEnd; i++) {
            lineActions[i] = { type: 'remove' };
        }
    }
}

// Build new lines array
const newLines = [];
for (let i = 0; i < lines.length; i++) {
    const action = lineActions[i];
    if (action === null) {
        newLines.push(lines[i]);
    } else if (action.type === 'replace') {
        newLines.push(action.content);
    }
    // 'remove' lines are skipped
}

fs.writeFileSync('vermilion.asm', newLines.join('\n'));

const removedLines = lines.length - newLines.length;
console.log(`Original: ${lines.length} lines`);
console.log(`New: ${newLines.length} lines`);
console.log(`Removed: ${removedLines} lines`);

// Count incbin directives added
const incbinCount = sectorRanges.filter(s => s.action === 'incbin').length;
const removeCount = sectorRanges.filter(s => s.action === 'remove').length;
console.log(`incbin directives added: ${incbinCount}`);
console.log(`Unreferenced labels removed: ${removeCount}`);
