#!/usr/bin/env node
// tools/audit_magic_numbers.js
//
// Uses vermilion.lst (generated by build.bat) to find raw hex immediate
// operands that are used in instructions but do not correspond to any
// symbolic constant defined in constants.asm.
//
// These are candidates to replace with named constants for clarity.
//
// Usage:
//   node tools/audit_magic_numbers.js [--lst <path>] [--threshold <N>] [--verbose]
//
// Defaults:
//   --lst        vermilion.lst  (relative to repo root)
//   --threshold  2              (report values that appear >= N times)
//
// Exit 0 always (this is a report, not a gate).
//
// Output: human-readable report to stdout.

'use strict';

const fs   = require('fs');
const path = require('path');

// ---------------------------------------------------------------------------
// Argument parsing
// ---------------------------------------------------------------------------

const ROOT = path.resolve(__dirname, '..');
const args = process.argv.slice(2);

function getArg(flag, def) {
  const i = args.indexOf(flag);
  return i !== -1 ? args[i + 1] : def;
}

const lstPath   = path.resolve(ROOT, getArg('--lst', 'vermilion.lst'));
const threshold = parseInt(getArg('--threshold', '2'), 10);
const verbose   = args.includes('--verbose');

if (!fs.existsSync(lstPath)) {
  console.error(`ERROR: listing file not found: ${lstPath}`);
  console.error('Run build.bat first to generate vermilion.lst');
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Step 1: Collect all symbolic constants from constants.asm
// ---------------------------------------------------------------------------
// We build two lookup structures:
//   valueToNames  — Map<normalizedHex, Set<name>>   (one value → multiple names)
//   namesToValue  — Map<name, normalizedHex>

const constPath = path.resolve(ROOT, 'constants.asm');
const CONST_RE  = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*(?:equ|=)\s*\$([0-9A-Fa-f]+)/i;

const valueToNames = new Map();   // '0x00FF' -> Set { 'MASK_LOW_BYTE', ... }
const namesToValue = new Map();

if (fs.existsSync(constPath)) {
  for (const rawLine of fs.readFileSync(constPath, 'utf8').split('\n')) {
    const line = rawLine.replace(/\r$/, '');
    const m = CONST_RE.exec(line);
    if (!m) continue;
    const name  = m[1];
    const value = parseInt(m[2], 16);
    const key   = '0x' + value.toString(16).toUpperCase().padStart(4, '0');
    if (!valueToNames.has(key)) valueToNames.set(key, new Set());
    valueToNames.get(key).add(name);
    namesToValue.set(name, key);
  }
}

// ---------------------------------------------------------------------------
// Step 2: Parse listing file — extract immediate hex values from real lines
// ---------------------------------------------------------------------------
// Real instruction lines start with an 8-digit hex ROM address.
// We extract every   #$XXXX   or   #$XXXXXXXX   operand from the source text.
//
// We skip:
//   - Comment-only listing lines (no ROM address prefix)
//   - Lines from the 00000000 "comment/macro expansion" zone
//   - VDP register longwords  #$8x... (VDP register writes are well-known)
//   - MOVEQ immediates (single byte, low signal)

const LINE_RE   = /^([0-9A-Fa-f]{8})\s/;         // real instruction line
const IMM_RE    = /#\$([0-9A-Fa-f]+)/g;           // immediate hex operand

// Values to skip from the report (well-understood hardware constants or
// values that are inherently anonymous):
const SKIP_VALUES = new Set([
  // VDP control values / common masks already covered by hw register names:
  '0x8F00', '0x8F02', '0x8100', '0x8104',
  // SR flags (covered by CPU convention):
  '0x0700', '0xF8FF', '0x2700', '0x2000',
  // Common bit counts / loop counts that are not constants:
  '0x0001', '0x0002', '0x0003', '0x0004',
  '0x0000', '0xFFFF',
]);

// Frequency count: normalizedKey -> { count, sites: [{address, srcLine}] }
const freq = new Map();

const lstLines = fs.readFileSync(lstPath, 'utf8').split('\n');

for (const rawLine of lstLines) {
  const line = rawLine.replace(/\r$/, '');
  const lm = LINE_RE.exec(line);
  if (!lm) continue;
  if (lm[1] === '00000000') continue;   // macro expansion / comment zone

  // Extract the source text portion (after the bytes column)
  // Listing format: XXXXXXXX  BYTES...  <tab>  source
  const tabIdx = line.indexOf('\t');
  const src = tabIdx !== -1 ? line.slice(tabIdx) : line.slice(40);

  // Skip pure comment lines in source
  if (src.trimStart().startsWith(';')) continue;

  // Strip inline comments
  const codePart = src.split(';')[0];

  let m;
  IMM_RE.lastIndex = 0;
  while ((m = IMM_RE.exec(codePart)) !== null) {
    const raw   = m[1];
    const value = parseInt(raw, 16);
    // Normalise to 4 hex digits for lookup (word-width), or 8 for longs
    const width = raw.length <= 4 ? 4 : 8;
    const key   = '0x' + value.toString(16).toUpperCase().padStart(width, '0');

    if (SKIP_VALUES.has(key)) continue;
    // Skip VDP register writes (high byte $8x–$Cx)
    if (value >= 0x8000 && value <= 0xCFFF && width === 4) continue;

    if (!freq.has(key)) freq.set(key, { count: 0, sites: [] });
    const entry = freq.get(key);
    entry.count++;
    if (verbose || entry.sites.length < 3) {
      entry.sites.push({ address: lm[1], srcLine: src.trim().slice(0, 100) });
    }
  }
}

// ---------------------------------------------------------------------------
// Step 3: Classify results
// ---------------------------------------------------------------------------
// For each value, check if it has a known constant.

const withSymbol    = [];  // has a constant — already named, just verify usage
const withoutSymbol = [];  // no constant — genuine magic number candidate

for (const [key, data] of freq.entries()) {
  if (data.count < threshold) continue;
  const names = valueToNames.get(key);
  if (names && names.size > 0) {
    withSymbol.push({ key, count: data.count, names: [...names], sites: data.sites });
  } else {
    withoutSymbol.push({ key, count: data.count, sites: data.sites });
  }
}

// Sort by frequency descending
withoutSymbol.sort((a, b) => b.count - a.count);
withSymbol.sort((a, b) => b.count - a.count);

// ---------------------------------------------------------------------------
// Step 4: Report
// ---------------------------------------------------------------------------

const LINE = '='.repeat(70);

console.log(LINE);
console.log('  Magic Number Audit — Sword of Vermilion');
console.log(`  Source: ${path.relative(ROOT, lstPath)}`);
console.log(`  Threshold: values appearing >= ${threshold} times`);
console.log(LINE);
console.log();

if (withoutSymbol.length === 0) {
  console.log('  No unnamed magic numbers found above threshold.');
} else {
  console.log(`  UNNAMED MAGIC NUMBERS (${withoutSymbol.length} values — add constants for these):`);
  console.log();
  for (const entry of withoutSymbol) {
    console.log(`  ${entry.key.padEnd(12)}  ${entry.count}x`);
    if (verbose) {
      for (const s of entry.sites) {
        console.log(`    [${s.address}] ${s.srcLine}`);
      }
    } else {
      // Show up to 2 example sites even without --verbose
      for (const s of entry.sites.slice(0, 2)) {
        console.log(`    [${s.address}] ${s.srcLine}`);
      }
      if (entry.count > 2) console.log(`    ... (${entry.count - 2} more)`);
    }
    console.log();
  }
}

console.log();
console.log(`  ALREADY NAMED (${withSymbol.length} values — verify inline uses match symbol):`);
console.log();
for (const entry of withSymbol.slice(0, 20)) {
  console.log(`  ${entry.key.padEnd(12)}  ${entry.count}x  →  ${entry.names.slice(0, 3).join(', ')}`);
}
if (withSymbol.length > 20) {
  console.log(`  ... (${withSymbol.length - 20} more; re-run with --verbose for full list)`);
}

console.log();
console.log(LINE);
console.log(`  Summary: ${withoutSymbol.length} unnamed | ${withSymbol.length} named`);
console.log(`           (threshold: >= ${threshold} occurrences)`);
console.log(LINE);
